### ISSUE TITLE
Shift Control C does nothing

### ISSUE THREAD

**Issue by ru-web-designer** [arshad/Sketch-Sass-Colors#1]
Sketch 3.4, OSX El Captain.

Have .sketch file with variables

![image](https://cloud.githubusercontent.com/assets/3310192/11341046/c422f0ac-9211-11e5-8dd9-2e1f97bda9ad.png)

Plugin says

![image](https://cloud.githubusercontent.com/assets/3310192/11341051/ca506f5e-9211-11e5-9cf9-769e8a94993f.png)

And then pressing shift + control + C does nothing with selected layer

![image](https://cloud.githubusercontent.com/assets/3310192/11341075/e5cd5df0-9211-11e5-8b13-08017c3f2363.png)

**Comment by ru-web-designer** [comment]
![image](https://cloud.githubusercontent.com/assets/3310192/11341424/773f9f5e-9213-11e5-82e4-7dfbf0971dd0.png)

**Comment by arshad** [comment]
Fixed. Thanks.
