### ISSUE TITLE
Variable name not displayed

### ISSUE THREAD

**Issue by playerzero** [arshad/Sketch-Sass-Colors#3]
Running Sketch 3.5.2 and when i Show Colors (via menu or keyboard shortcut), i only see hex values. I have added my color variables through the plugin's Configure menu. Seems the plugin is working but just not displaying my variables. Happy to help troubleshoot. Any chance it could be because i'm on the trial version? Thanks!

**Comment by arshad** [comment]
Looks like there was an issue with case sensitive colors. Fixed it.

Can you try the new release 1.1? https://github.com/arshad/Sketch-Sass-Colors/archive/1.1.zip

**Comment by playerzero** [comment]
Yup, works perfectly now. Very helpful plugin. Thanks!
