### ISSUE TITLE
is it working on Sketch 41.2?

### ISSUE THREAD

**Issue by alfupe** [arshad/Sketch-Sass-Colors#5]
Hi,

The plugin says "sass variables saved succesfully" when saving variables. Then if I select nothing press control + shift + c, the plugin says "no colors found", but if I select an object that is using for instance a fill with the same hex value of any of the variables and press control + shift + c, the plugin says nothing... Is it working on Sketch 41.2?

Thanks

**Comment by arshad** [comment]
@alfupe let me test it against this sketch version and report back.

**Comment by alfupe** [comment]
Thanks a lot @arshad!

**Comment by arshad** [comment]
@alfupe Figured it out. `MSColor.hexValue` has been deprecated in Sketch 41.2. Fixed it. Tagging a new release.

**Comment by arshad** [comment]
@alfupe done. You can now download version 1.3: https://github.com/arshad/Sketch-Sass-Colors/releases/tag/1.3

**Comment by alfupe** [comment]
It's working perfectly although the plugin says is version 1.2

Thanks a lot ;-)
